apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:latest
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
        env:
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "home_automation"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "sensor_data_bucket"
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: "adminToken123"
        - name: DOCKER_INFLUXDB_HOST
          value: "influxdb"
        - name: DOCKER_INFLUXDB_PORT
          value: "8086"
        - name: DOCKER_MQTT_BROKER_HOST
          value: "mqttbroker"
        - name: DOCKER_MQTT_BROKER_PORT
          value: "1883"

      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
